name: Build Android Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ModMenu_APK
          # Los APKs compilados por Gradle suelen estar aquí:
          path: app/build/outputs/apk/debug/ 

